### ISSUE TITLE
OctopOS Prime Merchandise Art Designs-1

### ISSUE THREAD

**Issue by aleyna0f** [octoposprime/op-design#100]
You are expected to design for OctopOS Prime in a merchandise art style.

**Comment by betulbodur00** [comment]
Merchandise art of OctopOs Prime and various arts:

![Başlıksız2272_20240512220330.png](https://github.com/octoposprime/op-design/assets/158744085/01a77dcf-a329-43b1-ae23-7d4806699bd1)

![Başlıksız2285_20240514170128.png](https://github.com/octoposprime/op-design/assets/158744085/d824e63d-d4f1-4e32-b114-285f46ab0213)

![Başlıksız2272_20240512215901.png](https://github.com/octoposprime/op-design/assets/158744085/0447c5ff-6387-42ec-a96c-b21cfd92ed52)

![Başlıksız2273_20240512231337.png](https://github.com/octoposprime/op-design/assets/158744085/4f9b161a-8d97-4033-8717-6c8d2e685512)

![Başlıksız2278_20240514152911.png](https://github.com/octoposprime/op-design/assets/158744085/de70932f-1ae9-4bf1-8b3f-7df52505b583)

![Başlıksız2277_20240513121214.png](https://github.com/octoposprime/op-design/assets/158744085/ce524f35-9120-4564-8603-9ee83daf960d)

![Başlıksız2271_20240512205652.png](https://github.com/octoposprime/op-design/assets/158744085/0e20be52-a003-47e9-bbbd-5241d7e127ff)

![Başlıksız2276_20240513173216.png](https://github.com/octoposprime/op-design/assets/158744085/aedc80e6-0e1a-461a-af3b-588281ff924b)
