### ISSUE TITLE
OctopOS Prime Sticker Designs-1

### ISSUE THREAD

**Issue by aleyna0f** [octoposprime/op-design#101]
You are expected to design sticker for OctopOS Prime with the expressions you want.

**Comment by betulbodur00** [comment]
OctopOs Prime stickers:

Overall Look:
![Başlıksız2311_20240525162432.png](https://github.com/octoposprime/op-design/assets/158744085/2f31b764-68f1-4c91-9e53-cae553114d0a)

Stickers:

![Başlıksız2344_20240525154941.png](https://github.com/octoposprime/op-design/assets/158744085/f6d21238-e336-4dd0-9aa1-2bf34d45dc2e)

![Başlıksız2342_20240525154710.png](https://github.com/octoposprime/op-design/assets/158744085/3f31c1ca-6257-4049-9b0c-8cf2bff845ce)

![Başlıksız2343_20240525162256.png](https://github.com/octoposprime/op-design/assets/158744085/251cab14-81f5-49b7-b293-3fd0f0906397)

![Başlıksız2342_20240525154552.png](https://github.com/octoposprime/op-design/assets/158744085/8b5e7d8d-375a-49b5-a2d9-c905b4b0b3e4)

![Başlıksız2342_20240525154522.png](https://github.com/octoposprime/op-design/assets/158744085/975cd666-1f3b-4c96-b1f2-463603be8ec9)

![Başlıksız2342_20240525154456.png](https://github.com/octoposprime/op-design/assets/158744085/05f2b39c-c2ab-451a-921e-9edfcadd4f99)

![Başlıksız2342_20240525154634.png](https://github.com/octoposprime/op-design/assets/158744085/75a04355-4c03-49d1-b6c3-5fdcb9d49218)

![Başlıksız2340_20240525154006.png](https://github.com/octoposprime/op-design/assets/158744085/64e5a8d6-cc99-4961-9d4c-bed964f520ec)

![Başlıksız2341_20240525154253.png](https://github.com/octoposprime/op-design/assets/158744085/c50776b2-61b7-41b2-8cca-ed76e4e787ad)

![Başlıksız2341_20240525154219.png](https://github.com/octoposprime/op-design/assets/158744085/0c88c025-7e9d-414e-bbec-758cc00c5840)

![Başlıksız2340_20240525154001.png](https://github.com/octoposprime/op-design/assets/158744085/1c8bd775-459a-4202-a0e1-7e675d1c521d)

![Başlıksız2342_20240525154418.png](https://github.com/octoposprime/op-design/assets/158744085/f7b3ef68-1e4a-42d3-a78f-3f7c3fddecb7)
