### ISSUE TITLE
OctopOS Prime Object Research-1

### ISSUE THREAD

**Issue by aleyna0f** [octoposprime/op-design#105]
Research different objects in 2D and find example images online. We will use these objects for OctopOS Prime. 

Example: - OctopOS Prime pen.
               - OctopOS Prime glass.

**Comment by hedil01** [comment]
In this research assignment, I researched different designs of hat and bag printing models for OctopOS Prime. I compiled my favorite images for you. I hope it will help you while designing.


![IMG_2620](https://github.com/octoposprime/op-design/assets/158466384/59ababb8-1c55-4af5-9681-c3df943fdb9c)
![IMG_2621](https://github.com/octoposprime/op-design/assets/158466384/b910945f-e274-4d68-84eb-bcaff63dfee8)
![IMG_2622](https://github.com/octoposprime/op-design/assets/158466384/6cb0b03f-ac7c-4a2a-941e-701773638807)
![IMG_2623](https://github.com/octoposprime/op-design/assets/158466384/05373af2-9415-4aa2-a7b7-3068f804b775)
![IMG_2624](https://github.com/octoposprime/op-design/assets/158466384/5f164042-b3a5-4059-a33f-2e8b5dc3d206)
![IMG_2625](https://github.com/octoposprime/op-design/assets/158466384/8a906332-f468-4920-a85d-790615caeab0)
![IMG_2626](https://github.com/octoposprime/op-design/assets/158466384/52f5d2b7-5417-4603-afbf-24f1dbfab1e2)
![IMG_2627](https://github.com/octoposprime/op-design/assets/158466384/cac40c46-9eda-46f6-b0cf-a135805b608a)
![IMG_2628](https://github.com/octoposprime/op-design/assets/158466384/06d83d45-a230-4cfe-bc98-aae45da95f37)
![IMG_2629](https://github.com/octoposprime/op-design/assets/158466384/4d6d96a6-26a0-4aa5-8c67-522c90f8d6e8)
![IMG_2630](https://github.com/octoposprime/op-design/assets/158466384/daeadfa6-67d2-4c50-ae9d-57ad1b9174d5)
![IMG_2631](https://github.com/octoposprime/op-design/assets/158466384/1082195f-bc3c-49b1-9114-6a359c0bd678)
![IMG_2632](https://github.com/octoposprime/op-design/assets/158466384/21087375-0514-4892-8ba3-7df32a46a872)
![IMG_2633](https://github.com/octoposprime/op-design/assets/158466384/3ffc2f35-0329-4d81-9667-d16f95a6d7ff)
![IMG_2634](https://github.com/octoposprime/op-design/assets/158466384/4d61b445-fadd-40b3-963f-35570ff1e067)
