### ISSUE TITLE
OctopOS Prime Business Card Design-1

### ISSUE THREAD

**Issue by aleyna0f** [octoposprime/op-design#106]
Design different models of business cards for OctopOS Prime.

The size of the card should be 8,5 x 5 cm.
There should be a photo of OctopOSPrime website on the back of the card and contact information and the logo on the front.

**Comment by ikramylmz** [comment]
My business card designs for OctopOSPrime
![1](https://github.com/octoposprime/op-design/assets/152586341/b5d70009-7bd0-427c-bd19-7178dad0e4f7)
![2](https://github.com/octoposprime/op-design/assets/152586341/c27c657f-0b10-4e6b-abd8-c05b6c7a4058)
![3](https://github.com/octoposprime/op-design/assets/152586341/be1efcf4-8c66-43b2-9f2d-2261b15fde4b)
![4](https://github.com/octoposprime/op-design/assets/152586341/747a577b-f870-40dd-82c4-97127bd2199d)
![5](https://github.com/octoposprime/op-design/assets/152586341/b3d6350d-4034-4c9b-8869-bb756443f9a9)
![6](https://github.com/octoposprime/op-design/assets/152586341/384c5c6d-b95c-4c45-b516-be6224eb5288)
![7](https://github.com/octoposprime/op-design/assets/152586341/25cffc8a-cd0e-4b5e-9ff1-58c3678f4792)
![8](https://github.com/octoposprime/op-design/assets/152586341/2cba1c30-92a9-49b9-bd76-9c8693409fdb)
![9](https://github.com/octoposprime/op-design/assets/152586341/cd146a4d-dd84-48c2-b937-61a59b8f02d2)

**Comment by ikramylmz** [comment]
![Uploading OctopOSPrime kartvizit arka.png…]()

**Comment by ikramylmz** [comment]
![OctopOSPrime kartvizit arka](https://github.com/octoposprime/op-design/assets/152586341/82cd2d8a-e5fa-4aef-bcd2-daf68634c969)
