### ISSUE TITLE
Backend Icons and Badges-1 (the first three badges)

### ISSUE THREAD

**Issue by aleyna0f** [octoposprime/op-design#11]
In the OctopOs Prime project, one of the 8 teams, namely the Backend Team, requires the following designs from the Design Team:

- Designing the main icon for the Backend Team
- Designing 10 badges that determine the levels of members in the Backend Team
    - Obtaining the outputs as an icon
     - Obtaining the outputs in PNG format

**The badge names for the Backend Team are listed below.**
1) Silver Seed
2) Budding Sprout
3) Shining Leaf
4) Wisdom Tree
5) Crystal River
6) Mountain of Thought
7) Star Voyager
8) Beacon Captain
9) Sun Throne
10) Galaxy Lord

The works in icon format (.ico extension files) will be uploaded to the op-design repository's **Src/2D/Badges/Backend/Ico** directory, and those in PNG format (.png extension files) will be uploaded to the op-design repository's **Src/2D/Badges/Backend/Png** directory.

**The standardization of file names for the uploaded files will be as follows:**
`<Date>-<description of the logo>(<size>).<file extension>`
Example:
07-03-24-op-logo-black-and-blue-colors-futuristic-laboratory-setting(1280x720).jpg
08-03-24-op-logo-sleek-and-futuristic-clean-white-background(1280x720).jpg

**Comment by aleyna0f** [comment]
@octoposprime/be-tl 

Could you write the content of the level badges representing the Backend Team?

**Comment by Sddilora** [comment]
Our content is a bit difficult to clarify, but we want our badges to clearly represent their intended meaning, giving them real-world significance.

**Comment by ikramylmz** [comment]
SILVER SEED

![Image](https://github.com/octoposprime/op-design/assets/152586341/d1f86c51-c9e7-42b6-b393-2d53748fcb96)

BUDDING SPROUD



![Image](https://github.com/octoposprime/op-design/assets/152586341/81b920f8-5383-439a-8755-a3cb4b15cde8)


SPARKLING LEAF



![Image](https://github.com/octoposprime/op-design/assets/152586341/dae3c83a-cec5-40ef-917d-3a107ff41f6a)

**Comment by Sddilora** [comment]
wonderful, very good work, thank you for your efforts

**Comment by ikramylmz** [comment]
you are welcome, it's my pleasure.
