### ISSUE TITLE
OctopOS Prime Emoji Designs-1

### ISSUE THREAD

**Issue by aleyna0f** [octoposprime/op-design#119]
You are expected to design emoji for OctopOS Prime with the expressions you want.

**Comment by betulbodur00** [comment]
OctopOs Prime Emojis (Part 1)


![Başlıksız2366_20240601180251.png](https://github.com/octoposprime/op-design/assets/158744085/dd11964b-7fe7-490a-a36e-84c590c4065a)

![Başlıksız2364_20240601175815.png](https://github.com/octoposprime/op-design/assets/158744085/26a409f9-eb1f-44a8-9d51-d44f7f7f6527)

![Başlıksız2363_20240601172503.png](https://github.com/octoposprime/op-design/assets/158744085/8ff56abc-55dc-4e1c-b60d-520c08ce159a)

![Başlıksız2360_20240601171500.png](https://github.com/octoposprime/op-design/assets/158744085/3b5a373a-8ed2-4ded-9dea-aade04f1fcfc)

![Başlıksız2362_20240601172012.png](https://github.com/octoposprime/op-design/assets/158744085/c8679264-bf18-46bc-a256-2c22ffbaab18)

![Başlıksız2360_20240601171421.png](https://github.com/octoposprime/op-design/assets/158744085/cb75affb-de54-4e98-aed8-a55abfc3500c)

![Başlıksız2360_20240601171325.png](https://github.com/octoposprime/op-design/assets/158744085/91c7d014-ec25-41ca-ab13-b69c44397323)

![Başlıksız2360_20240601171402.png](https://github.com/octoposprime/op-design/assets/158744085/967e6c2f-6405-4e44-a50b-5354ab7e71d8)

![Başlıksız2360_20240601171308.png](https://github.com/octoposprime/op-design/assets/158744085/bc8dea78-c54f-44c4-ad02-a532f291c6b4)

![Başlıksız2360_20240601171249.png](https://github.com/octoposprime/op-design/assets/158744085/09c6eb86-e0e5-46ba-90bc-abcbff5cf7b5)

![Başlıksız2360_20240601171218.png](https://github.com/octoposprime/op-design/assets/158744085/90b17ba2-f45f-4bbe-9f4a-6858fd67d315)

![Başlıksız2360_20240601171136.png](https://github.com/octoposprime/op-design/assets/158744085/de786ea3-9c7f-4c4f-abd0-51d219bb2fa8)

![Başlıksız2360_20240601171100.png](https://github.com/octoposprime/op-design/assets/158744085/c4a6a7e4-6b37-475c-b14c-36b7b94a1e15)

![Başlıksız2360_20240601171029.png](https://github.com/octoposprime/op-design/assets/158744085/bf4e696a-72c4-473c-ad5f-b1b31f873d26)

![Başlıksız2360_20240601171007.png](https://github.com/octoposprime/op-design/assets/158744085/dbfd7bb5-20af-4fc1-a369-798b80608c0c)

![Başlıksız2360_20240601170934.png](https://github.com/octoposprime/op-design/assets/158744085/ce412c5c-e0eb-4a55-9e8d-023e1ee93ac9)

![Başlıksız2360_20240601170917.png](https://github.com/octoposprime/op-design/assets/158744085/ef980409-a9b8-4ed4-8a6f-88b35b09beb8)

![Başlıksız2360_20240601170902.png](https://github.com/octoposprime/op-design/assets/158744085/61de4632-bb71-4763-b5af-4bd944bdbb64)

![Başlıksız2360_20240601170820.png](https://github.com/octoposprime/op-design/assets/158744085/cbd45c6e-e1ca-4a6c-9301-cb9d467838db)

![Başlıksız2360_20240601170845.png](https://github.com/octoposprime/op-design/assets/158744085/671a0423-577f-4604-b513-0394917d9b0f)

![Başlıksız2360_20240601170757.png](https://github.com/octoposprime/op-design/assets/158744085/27644090-37d2-4c4e-a47c-db81ba6ce805)
