### ISSUE TITLE
DevOps Icons and Badges-1 (the first three badges)

### ISSUE THREAD

**Issue by aleyna0f** [octoposprime/op-design#12]
In the OctopOs Prime project, one of the 8 teams, namely the DevOps Team, requires the following designs from the Design Team:

- Designing the main icon for the DevOps Team
- Designing 10 badges that determine the levels of members in the DevOps Team
    - Obtaining the outputs as an icon
     - Obtaining the outputs in PNG format

**The badge names for the DevOps Team are listed below.**

**1) Rookie** 
The first step is to gain a general understanding of the basic principles, tools, and practices of DevOps. Those who successfully complete this step earn the Rookie rank.

**2) Penguin** 
Next, it is necessary to learn the basics of Linux operating systems and gain skills in working with Linux-based systems. Those who pass this step advance to the Penguin rank.

**3) Author** 
Proficiency in coding is crucial in DevOps. You can start by learning a programming language and improve your skills by learning software development processes and tools. Those who successfully pass this step are entitled to the Author rank.

**4) Postman** 
Learning and using CI-CD tools is critical for automating software development processes. Those who succeed in this step are promoted to the Postman rank.

**5) Helmsman** 
Learning container technologies like Docker and orchestration tools like Kubernetes enables the rapid and reliable deployment of applications. The Helmsman rank is earned by those who successfully complete this step.

**6) Thor** 
Learning the fundamentals of cloud technologies and migrating infrastructure to the cloud are essential. Those who pass this step advance to the Thor rank.

**7) Operator** 
Automation reduces manual tasks and automates repeatable tasks. Those who develop automation skills earn the Operator rank.

**8) Sentinel** 
Learning to use monitoring and logging tools to monitor application performance and identify issues is important. The Sentinel rank is earned by those who successfully complete this step.

**9) Guardian** 
Security is an integral part of any DevOps process. Those who learn to identify security vulnerabilities, adhere to secure coding principles, and configure secure network infrastructure are promoted to the Guardian rank.

**10) Architect** 
You are a DevOps specialist. You are open to continuous learning and have the ability to take on leadership roles.

The works in icon format (.ico extension files) will be uploaded to the op-design repository's **Src/2D/Badges/DevOps/Ico** directory, and those in PNG format (.png extension files) will be uploaded to the op-design repository's **Src/2D/Badges/DevOps/Png** directory.

**The standardization of file names for the uploaded files will be as follows:**
`<Date>-<description of the logo>(<size>).<file extension>`
Example:
07-03-24-op-logo-black-and-blue-colors-futuristic-laboratory-setting(1280x720).jpg
08-03-24-op-logo-sleek-and-futuristic-clean-white-background(1280x720).jpg

**Comment by husamettinarabaci** [comment]
I think It can be separated into two or three parts.
DevOps Icons and Badges-1 ( It can include the first three badges.)
DevOps Icons and Badges-2 ( It can include the second three badges.)
DevOps Icons and Badges-3 ( It can include others.)

In this way, You can separate real iterations of these issues.
DevOps Icons and Badges-1 = iteration11
DevOps Icons and Badges-1 = iteration12
DevOps Icons and Badges-1 = iteration13

**Comment by esmanrshn** [comment]
Badges I made for the DevOps team


![ROOKIE](https://github.com/octoposprime/op-design/assets/128504391/c3cf3c01-8ed6-4f62-b09d-a2f8f0b47443)

![PENGUIN](https://github.com/octoposprime/op-design/assets/128504391/893f197e-4405-4fb1-802b-98891ce859e6)

![AUTHOR](https://github.com/octoposprime/op-design/assets/128504391/22319abc-1a81-4431-a4ce-f16877d997e4)
