### ISSUE TITLE
OctopOS Prime Brochures-1 (soft themed)

### ISSUE THREAD

**Issue by aleyna0f** [octoposprime/op-design#124]
OctopOS Prime project;

**1- Digital concept:** Electronic-Mechanic, Backend, Web, Mobile
2- Art concept 

Design the "Digital Concept" leaflet with a soft theme among the leaflets to be divided into two.

The size of the flyer should be 1,122 x 792 pixels.

**Comment by ikramylmz** [comment]
my design of digital brochures
![5](https://github.com/octoposprime/op-design/assets/152586341/ce89a66a-db66-421a-be73-7e1a69da6485)
![6](https://github.com/octoposprime/op-design/assets/152586341/9bb034a8-3435-4c7f-a23e-f30982ae8007)
