### ISSUE TITLE
OctopOS Prime Brochures-2 (soft themed)

### ISSUE THREAD

**Issue by aleyna0f** [octoposprime/op-design#127]
OctopOS Prime project;

1- Digital concept
**2- Art concept:** Ceramic, DevOps, Design, Game

Design the "Art Concept" flyer with a dark theme among the flyers to be divided into two.

The size of the flyer should be 1,122 x 792 pixels.

**Comment by ikramylmz** [comment]
my design of art concept brochures
![8](https://github.com/octoposprime/op-design/assets/152586341/16f28b1a-5dbb-44be-898d-b9e82e62ac89)
![7](https://github.com/octoposprime/op-design/assets/152586341/b5970ead-ee28-4f22-8995-842daee130d5)
