### ISSUE TITLE
Game Icons and Badges-1 (the first three badges)

### ISSUE THREAD

**Issue by aleyna0f** [octoposprime/op-design#13]
In the OctopOs Prime project, one of the 8 teams, namely the Game Team, requires the following designs from the Design Team:

- Designing the main icon for the Backend Team
- Designing 10 badges that determine the levels of members in the Backend Team
    - Obtaining the outputs as an icon
     - Obtaining the outputs in PNG format

**The badge names for the Game Team are listed below.**

**1) New Apprentice**
Skills to Learn: Unity user interface (UI), basic game objects, and working with scenes.
Badge Name: Pixel Hunter

**2) Code Wizard Apprentice**
Skills to Learn: Basics of C#, simple script writing, variables, loops, and conditions.
Badge Name: Code Sorcerer

**3) Scene Artist**
Skills to Learn: Scene editing, fundamentals of lighting, camera settings.
Badge Name: World Creator

**4) Game Mechanics Expert**
Skills to Learn: Usage of physics engine, collision detectors, character control.
Badge Name: Mechanical Engineer

**5) Graphics Guru**
Skills to Learn: Shaders, materials, and texture mapping.
Badge Name: Visual Effects Master

**6) Sound Effect Artist**
Skills to Learn: Integration of sound effects and music, 3D sound positioning.
Badge Name: Symphony Director

**7) AI Architect**
Skills to Learn: Basic artificial intelligence (AI) behaviors, enemy AI, tracking and evasion behaviors.
Badge Name: Intelligence Engineer

**8) Performance Wizard**
Skills to Learn: Game performance optimization, memory management, resolution, and render settings.
Badge Name: Speed Master

**9) Network Master**
Skills to Learn: Network programming for multiplayer games, data synchronization.
Badge Name: Network Architect

**10) Legendary Creator**
Skills to Learn: VR/AR development, advanced graphics and performance techniques, complex AI systems.
Badge Name: Reality Weaver

The works in icon format (.ico extension files) will be uploaded to the op-design repository's Src/2D/Badges/Game/Ico directory, and those in PNG format (.png extension files) will be uploaded to the op-design repository's Src/2D/Badges/Game/Png directory.

**The standardization of file names for the uploaded files will be as follows:**
`<Date>-<description of the logo>(<size>).<file extension>`
Example:
07-03-24-op-logo-black-and-blue-colors-futuristic-laboratory-setting(1280x720).jpg
08-03-24-op-logo-sleek-and-futuristic-clean-white-background(1280x720).jpg

**Comment by nurbeyzaoztrk** [comment]
The first three badges awarded to the game team.

Badge Name: Pixel Hunter
![Image](https://github.com/octoposprime/op-design/assets/120026216/a9146baf-d926-4575-82c9-7e32b7dcd0ff)

Badge Name: Code Sorcerer
![Image](https://github.com/octoposprime/op-design/assets/120026216/8970c07a-59c0-4128-9c05-318fff96d2fd)

Badge Name: World Creator
![Image](https://github.com/octoposprime/op-design/assets/120026216/4444a2bb-2cd0-4404-8ddf-b1a4d4659c6b)
