### ISSUE TITLE
Docs Icons and Badges-1 (the first three badges)

### ISSUE THREAD

**Issue by aleyna0f** [octoposprime/op-design#14]
In the OctopOs Prime project, one of the 8 teams, namely the Docs Team, requires the following designs from the Design Team:

- Designing the main icon for the Docs Team
- Designing 10 badges that determine the levels of members in the Docs Team
    - Obtaining the outputs as an icon
     - Obtaining the outputs in PNG format

**The badge names for the Docs Team are listed below.**

**1) Proofreader** 
Responsible for correcting spelling and punctuation errors. Team members at this level identify and correct grammar and spelling mistakes in documents.

**2) Document Editor** 
Responsible for reviewing a specific document to ensure consistency and checking the scope of the document. Team members at this level work to ensure the integrity of documents.

**3) Emerging Writer** 
Individuals at this level begin to contribute to documents and also start adding their own ideas and knowledge. They not only improve the content of specific documents but also integrate their own experiences, knowledge, and suggestions into documents. They take on a more active role in creating written documents and make unique contributions to documents based on their expertise.

**4) Technical Writer** 
Responsible for expressing technical topics in an understandable manner. Team members at this level have written and oral communication skills to convey technical information in a user-friendly way.

**5) Project Lead & Content Manager** 
Individuals at this level have the ability to write entire projects and manage subordinates. They lead a specific project and are responsible for creating all project documents. They also manage team performance, set project goals, and ensure the smooth progress of the process. They possess both technical and managerial skills and produce effective documents in collaboration with their team.

**6) Global Project Observer & Idea Integrator** 
Individuals at this level follow projects worldwide on a daily basis and integrate ideas from these projects into their own projects. They not only edit existing documents but also follow innovations and best practices from external sources. They gather information from different sources every day, track new trends and developments, and integrate this information into their own projects. Thus, they ensure that documents are up-to-date and innovative, increase the competitiveness of projects, and encourage continuous improvement.

**7) Project Presenter & Fundraiser** 
Individuals at this level have the ability to write and present projects on online platforms such as Kickstarter and Indiegogo. They can successfully promote and present projects on online platforms to raise funds for a project. They have effective communication skills to promote projects, influence the target audience, and raise donations or investments. They can also clearly express the vision and potential of the project and persuade relevant stakeholders. With these skills, they can develop strategic plans to increase and sustain the financial success of projects.

**8) Innovator & Cross-Domain Project Strategist**
 Individuals at this level can find and implement ideas for projects needed worldwide by utilizing their research and experiences in all areas of the company. They are equipped with a comprehensive vision and extensive knowledge and can analyze trends, needs, and opportunities in different fields. They can develop strategic plans to successfully implement projects, manage resources, and coordinate all processes of the project. They can also generate creative solutions and enhance the impact of projects with innovative approaches.

**9) Product Hunter & Competition Champion**
 Individuals at this level have the talent and qualifications to make their projects the first in competitions such as Product Hunt. They have advanced skills and experience and can effectively promote their projects, influence the target audience, and convince the jury. They can also successfully position their projects in the competitive market and highlight their superior qualities. They can generate creative solutions, develop their projects with innovative approaches, and demonstrate superior performance. This level, called "Product Hunter," enables individuals to effectively use all resources to achieve success and lead their projects in the market.

**10) Global Project Management Maestro & Entrepreneur** 
Individuals at this level have the ability to establish and successfully manage a project writing company that caters to global markets. They are equipped with a comprehensive vision, leadership skills, and business knowledge. They can effectively manage project writing processes, understand customer needs, and provide the best solutions. They can also develop business strategies, manage marketing and sales activities, and implement strategies to grow the company. Individuals at this level, referred to as "Global Project Management Maestro & Entrepreneur," have the skills necessary to rise to a leadership position in the project writing industry and successfully represent their company internationally.

The works in icon format (.ico extension files) will be uploaded to the op-design repository's **Src/2D/Badges/Docs/Ico** directory, and those in PNG format (.png extension files) will be uploaded to the op-design repository's **Src/2D/Badges/Docs/Png** directory.

**The standardization of file names for the uploaded files will be as follows:**
`<Date>-<description of the logo>(<size>).<file extension>`
Example:
07-03-24-op-logo-black-and-blue-colors-futuristic-laboratory-setting(1280x720).jpg
08-03-24-op-logo-sleek-and-futuristic-clean-white-background(1280x720).jpg

**Comment by aleyna0f** [comment]
The first 3 level badges I designed for the Docs team.



1) Proofreader


![1](https://github.com/octoposprime/op-design/assets/118018067/532ea92d-bfa6-46d4-98e9-3862b2312a50)



2) Document Editor


![DocumentEditor](https://github.com/octoposprime/op-design/assets/118018067/3eea4ada-cdaf-47ac-8b55-ea4074142445)



3) Emerging Writer


![EmergingWriter](https://github.com/octoposprime/op-design/assets/118018067/13aa6bd1-df45-4f4c-aefe-193cd68927fe)

**Comment by mzarabaci** [comment]
![1](https://github.com/octoposprime/op-design/assets/158720216/46f87446-f3c5-42a8-9dda-9066248685f8)
![2](https://github.com/octoposprime/op-design/assets/158720216/cb724cda-e179-415f-909f-8382b944ace6)
![3](https://github.com/octoposprime/op-design/assets/158720216/836ba850-7c42-424e-89a4-bc435e76a377)
