### ISSUE TITLE
Web Icons and Badges-1 (the first three badges)

### ISSUE THREAD

**Issue by aleyna0f** [octoposprime/op-design#15]
In the OctopOs Prime project, one of the 8 teams, namely the Web Team, requires the following designs from the Design Team:

- Designing the main icon for the Web Team
- Designing 10 badges that determine the levels of members in the Web Team
    - Obtaining the outputs as an icon
     - Obtaining the outputs in PNG format

**The badge names for the Web Team are listed below.**

**1) HTML Sorcerer** 
Master the basic HTML structure and tags skillfully.

**2) CSS Crusader**
Master CSS styling and layout techniques to visually enhance your web pages.

**3) JavaScript Jedi**
Explore the power of JavaScript and make your web pages interactive.

**4) Responsive Guardian:**
Optimize user experience by creating websites that adapt to every device.

**5) DOM Navigator** 
Control your web pages proficiently using the Document Object Model (DOM).

**6) Framework Hero**
Develop powerful web applications by skillfully using popular web frameworks.

**7) API Overlord** 
Skillfully use APIs to exchange data between applications.

**8) Version Control Emperor** 
Skillfully use version control systems for collaborative development.

**9) Security Sentinel** 
Develop and protect your web applications securely and robustly.

**10) Full-Stack Galaxy Lord:** 
Master both front-end and back-end development and dominate the web universe.

The works in icon format (.ico extension files) will be uploaded to the op-design repository's **Src/2D/Badges/Web/Ico** directory, and those in PNG format (.png extension files) will be uploaded to the op-design repository's **Src/2D/Badges/Web/Png** directory.

**The standardization of file names for the uploaded files will be as follows:**
`<Date>-<description of the logo>(<size>).<file extension>`
Example:
07-03-24-op-logo-black-and-blue-colors-futuristic-laboratory-setting(1280x720).jpg
08-03-24-op-logo-sleek-and-futuristic-clean-white-background(1280x720).jpg

**Comment by suhedadogan50** [comment]
Web team first three badges.


1) HTML Sorcerer
![Image](https://github.com/octoposprime/op-design/assets/135768038/794a43a0-85dc-42c8-9cad-e0c15814d762)


2) CSS Crusader
![Image](https://github.com/octoposprime/op-design/assets/135768038/7534d6c1-4736-45be-a41b-b0185460c59d)


3) JavaScript Jedi
![Image](https://github.com/octoposprime/op-design/assets/135768038/9a301de4-5cae-4e6c-b420-6244162da7bd)

**Comment by suhedadogan50** [comment]
Fourth badge of the web team Responsive Guardian




![Image](https://github.com/octoposprime/op-design/assets/135768038/27befed3-16bd-43b6-b759-0c995a75d8b8)
