### ISSUE TITLE
Design Icons and Badges-1 ( the first three badges)

### ISSUE THREAD

**Issue by aleyna0f** [octoposprime/op-design#17]
In the OctopOs Prime project, one of the 8 teams, namely the Design Team, requires the following designs from the Design Team:

- Designing the main icon for the Design Team
- Designing 10 badges that determine the levels of members in the Design Team
    - Obtaining the outputs as an icon
     - Obtaining the outputs in PNG format

**The badge names for the Design Team are listed below.**

**1) Discovery Voyager**
Illustrator: Explore the interface, learn basic tools, and drawing techniques.
Blender: Explore the interface, learn basic modeling techniques, and navigation.

**2) Vector and Modeling Master**
Illustrator: Discover the power of vector drawing, design logos, icons, and illustrations.
Blender: Start creating simple 3D models.

**3) Color and Texture Alchemist**
Illustrator: Solve color theory, create eye-catching palettes.
Blender: Add texture and color to your models, making them realistic and appealing.

**4) Master of Letters and Animation**
Illustrator: Enhance your designs with meaning and visual interest using typography.
Blender: Prepare to animate your models by learning rigging and animation techniques.

**5) Layers and Motion Wizard**
Illustrator: Organize your designs with layers, create complex illustrations.
Blender: Learn to move your models realistically and smoothly.

**6) Effect and Light Master**
Illustrator: Add special effects and textures to your designs with effect tools.
Blender: Add depth and atmosphere to your models using light and shadow.

**7) Pattern and Camera Sorcerer**
Illustrator: Add rhythm and dynamism to your designs with pattern creation techniques.
Blender: Create impressive visuals using different camera angles and lenses.

**8) Visual and Simulation Wizard**
Illustrator: Enhance and enrich your designs using visual effects (VFX).
Blender: Create realistic effects using particle systems and physics simulations.

**9) Art and Render Hero**
Illustrator & Blender: Create 2D and 3D artworks reflecting your own style and vision.
Blender: Learn to turn your models into high-quality visuals.

**10) Gateway to Infinity**
Keep evolving and exploring innovations.
Embark on new horizons in the infinite universe of 2D and 3D design.

The works in icon format (.ico extension files) will be uploaded to the op-design repository's **Src/2D/Badges/Design/Ico** directory, and those in PNG format (.png extension files) will be uploaded to the op-design repository's **Src/2D/Badges/Design/Png** directory.

**The standardization of file names for the uploaded files will be as follows:**
`<Date>-<description of the logo>(<size>).<file extension>`
Example:
07-03-24-op-logo-black-and-blue-colors-futuristic-laboratory-setting(1280x720).jpg
08-03-24-op-logo-sleek-and-futuristic-clean-white-background(1280x720).jpg

**Comment by betulbodur00** [comment]
The first 3 badges for the design team.

First badge 

![Başlıksız2104_20240404233446.png](https://github.com/octoposprime/op-design/assets/158744085/ebd8a1a2-766b-4633-a913-c0dd141d573e)

![Başlıksız2113_20240405201114.png](https://github.com/octoposprime/op-design/assets/158744085/55d50d7f-0dac-49fa-af67-ce65ba113d6f)

Second badge

![Başlıksız2120_20240423104252.png](https://github.com/octoposprime/op-design/assets/158744085/6c679c0c-0121-4eac-b84a-2c1d8c185c6d)

![Başlıksız2105_20240423104224.png](https://github.com/octoposprime/op-design/assets/158744085/1e6142f7-cd62-4f25-9fb2-903e6ed0aa18)

Third badge

![Başlıksız2106_20240405014146.png](https://github.com/octoposprime/op-design/assets/158744085/742bffea-a4d4-4e11-b167-63516bb941c7)

![Başlıksız2111_20240405201029.png](https://github.com/octoposprime/op-design/assets/158744085/51487809-edeb-4b58-a52f-10b301dca16b)

**Comment by betulbodur00** [comment]
Non Pixelated Design Badges (1-3)

1st Badge
![Başlıksız2228.png](https://github.com/octoposprime/op-design/assets/158744085/5970fa96-18f1-4917-b0cd-9524d5b3eeaf)

2nd Badge
![Başlıksız2229.png](https://github.com/octoposprime/op-design/assets/158744085/6a50a51a-6050-4881-957e-55881b33ff01)

3rd Badge
![Başlıksız2235.png](https://github.com/octoposprime/op-design/assets/158744085/aa66d9f2-efbc-446a-8439-3a603fa01da6)

**Comment by betulbodur00** [comment]
Non Pixelated Design Badges (1-3)

1st Badge
![Başlıksız2228.png](https://github.com/octoposprime/op-design/assets/158744085/5970fa96-18f1-4917-b0cd-9524d5b3eeaf)

2nd Badge
![Başlıksız2235.png](https://github.com/octoposprime/op-design/assets/158744085/9a70125c-5512-41fc-8012-f663d206e96b)

3rd Badge
![Başlıksız2229.png](https://github.com/octoposprime/op-design/assets/158744085/f013f0b2-8c82-4f90-a1a0-574543ad428a)
