### ISSUE TITLE
Backend Icons and Badges-2 (one badge)

### ISSUE THREAD

**Issue by aleyna0f** [octoposprime/op-design#20]
In the OctopOs Prime project, one of the 8 teams, namely the Backend Team, requires the following designs from the Design Team:

- Designing the main icon for the Backend Team
- Designing 10 badges that determine the levels of members in the Backend Team
    - Obtaining the outputs as an icon (32x32)
     - Obtaining the outputs in PNG format (1080x1080)

**The badge names for the Backend Team are listed below.**
1) Silver Seed
2) Budding Sprout
3) Shining Leaf
4) Wisdom Tree +
5) Crystal River
6) Mountain of Thought
7) Star Voyager
8) Beacon Captain
9) Sun Throne
10) Galaxy Lord

The works in icon format (.ico extension files) will be uploaded to the op-design repository's **Src/2D/Badges/Backend/Ico** directory, and those in PNG format (.png extension files) will be uploaded to the op-design repository's **Src/2D/Badges/Backend/Png** directory.

**The standardization of file names for the uploaded files will be as follows:**
`<Date>-<description of the logo>(<size>).<file extension>`
Example:
07-03-24-op-logo-black-and-blue-colors-futuristic-laboratory-setting(1280x720).jpg
08-03-24-op-logo-sleek-and-futuristic-clean-white-background(1280x720).jpg

**Comment by ikramylmz** [comment]
WISDOM TREE



![Image](https://github.com/octoposprime/op-design/assets/152586341/085a7f03-e3eb-405c-a97b-eb4ee589f32a)
