### ISSUE TITLE
Design Icons and Badges-2 (one badge)

### ISSUE THREAD

**Issue by aleyna0f** [octoposprime/op-design#26]
In the OctopOs Prime project, one of the 8 teams, namely the Design Team, requires the following designs from the Design Team:

- Designing the main icon for the Design Team
- Designing 10 badges that determine the levels of members in the Design Team
    - Obtaining the outputs as an icon (32x32)
     - Obtaining the outputs in PNG format (1080x1080)

**The badge names for the Design Team are listed below.**

**1) Discovery Voyager**
Illustrator: Explore the interface, learn basic tools, and drawing techniques.
Blender: Explore the interface, learn basic modeling techniques, and navigation.

**2) Vector and Modeling Master**
Illustrator: Discover the power of vector drawing, design logos, icons, and illustrations.
Blender: Start creating simple 3D models.

**3) Color and Texture Alchemist**
Illustrator: Solve color theory, create eye-catching palettes.
Blender: Add texture and color to your models, making them realistic and appealing.

**4) Master of Letters and Animation**   +
Illustrator: Enhance your designs with meaning and visual interest using typography.
Blender: Prepare to animate your models by learning rigging and animation techniques.

**5) Layers and Motion Wizard**
Illustrator: Organize your designs with layers, create complex illustrations.
Blender: Learn to move your models realistically and smoothly.

**6) Effect and Light Master**
Illustrator: Add special effects and textures to your designs with effect tools.
Blender: Add depth and atmosphere to your models using light and shadow.

**7) Pattern and Camera Sorcerer**
Illustrator: Add rhythm and dynamism to your designs with pattern creation techniques.
Blender: Create impressive visuals using different camera angles and lenses.

**8) Visual and Simulation Wizard**
Illustrator: Enhance and enrich your designs using visual effects (VFX).
Blender: Create realistic effects using particle systems and physics simulations.

**9) Art and Render Hero**
Illustrator & Blender: Create 2D and 3D artworks reflecting your own style and vision.
Blender: Learn to turn your models into high-quality visuals.

**10) Gateway to Infinity**
Keep evolving and exploring innovations.
Embark on new horizons in the infinite universe of 2D and 3D design.

The works in icon format (.ico extension files) will be uploaded to the op-design repository's **Src/2D/Badges/Design/Ico** directory, and those in PNG format (.png extension files) will be uploaded to the op-design repository's **Src/2D/Badges/Design/Png** directory.

**The standardization of file names for the uploaded files will be as follows:**
`<Date>-<description of the logo>(<size>).<file extension>`
Example:
07-03-24-op-logo-black-and-blue-colors-futuristic-laboratory-setting(1280x720).jpg
08-03-24-op-logo-sleek-and-futuristic-clean-white-background(1280x720).jpg

**Comment by betulbodur00** [comment]
4th badge for the design design.

![Başlıksız2116_20240407223602.png](https://github.com/octoposprime/op-design/assets/158744085/0c6dc000-0ef8-4484-92d5-1d89d87497df)

![Başlıksız2115_20240407223541.png](https://github.com/octoposprime/op-design/assets/158744085/a01e3ffd-5c94-4505-a795-8d416a0be654)

**Comment by betulbodur00** [comment]
Non Pixelated Design Badge (4)

![Başlıksız2231_Geri Yüklendi2.png](https://github.com/octoposprime/op-design/assets/158744085/fd4a556c-4dc8-4429-95be-f973e5b11a4f)
