### ISSUE TITLE
OctopOS Prime Emoji Designs-2

### ISSUE THREAD

**Issue by aleyna0f** [octoposprime/op-design#293]
You are expected to design emoji for OctopOS Prime with the expressions you want.

**Comment by betulbodur00** [comment]
Emoji Designs (Part 2):

![Disgusted OctopOs Prime Emoji.png](https://github.com/user-attachments/assets/e072adf0-fa2c-4923-80fc-1c16fc336522)

![Dumbfounded OctopOs Prime Emoji.png](https://github.com/user-attachments/assets/85e23768-a946-4f4b-94e6-6387c0d54861)

![Overwhelmed OctopOs Prime Emoji.png](https://github.com/user-attachments/assets/77dc7b89-c776-4a0b-830c-bbdc5e476a85)

![Furious OctopOs Prime Emoji.png](https://github.com/user-attachments/assets/b1da2ed1-15f8-4959-b5bc-103d646886a2)

![Eyes Closed OctopOs Prime Emoji.png](https://github.com/user-attachments/assets/42659f7e-b9eb-41cd-8e86-211a1f9156a2)

![Know-It-All OctopOs Prime Emoji.png](https://github.com/user-attachments/assets/5608b89f-33ab-4c76-a978-7707ad07b19b)

![Shocked OctopOs Prime Emoji.png](https://github.com/user-attachments/assets/fce858b9-d7aa-4a3a-8588-a0c9d28f89d8)

![Silly OctopOs Prime Emoji.png](https://github.com/user-attachments/assets/1dd7f0a7-47ce-4deb-b7c8-5618a15a71f2)

![Bothered OctopOs Prime Emoji.png](https://github.com/user-attachments/assets/0ef6fa83-e067-4e9a-852e-1c6d0998a519)

![Confused OctopOs Prime Emoji.png](https://github.com/user-attachments/assets/428c96e0-41a8-4296-9be8-4c3ee9e34216)

![Disappointed OctopOs Prime Emoji.png](https://github.com/user-attachments/assets/1de92d89-d50d-4e7d-88af-61aa3c386937)

![Joyful OctopOs Prime Emoji.png](https://github.com/user-attachments/assets/3c6743a0-d106-47fb-9763-6d8d7d86da31)

![Emotional OctopOs Prime Emoji.png](https://github.com/user-attachments/assets/a3daa606-f5b8-4d7f-a660-76fac373dc3f)

![Bemused OctopOs Prime Emoji.png](https://github.com/user-attachments/assets/500b5735-6769-4576-9e54-cba2ca2dd783)

![Sensitive OctopOs Prime Emoji.png](https://github.com/user-attachments/assets/bc23a2b1-a68e-4c75-a651-672417a69e34)

![Teary OctopOs Prime Emoji.png](https://github.com/user-attachments/assets/385e9f37-8b60-45ce-b59f-9a5d2ed7e30e)

![Angry OctopOs Prime Emoji.png](https://github.com/user-attachments/assets/e44ca50e-3725-4e79-a5c4-c3a6dae1a802)

![Dissatisfied OctopOs Prime Emoji.png](https://github.com/user-attachments/assets/022de13b-0b36-42ca-87fd-4e89f5e84141)

![Sleepy OctopOs Prime Emoji (2).png](https://github.com/user-attachments/assets/b9fa0fa3-4953-4c11-b58d-84564765bff4)

![Doubtful OctopOs Prime Emoji.png](https://github.com/user-attachments/assets/d928c626-6edc-4096-ada7-f72eff1e4d05)

![Confused OctopOs Prime Emoji (2).png](https://github.com/user-attachments/assets/29ecf54a-5faa-4186-b4a5-a9f29c1aa5d4)
