### ISSUE TITLE
OctopOS Prime Fairy Tale Frames

### ISSUE THREAD

**Issue by aleyna0f** [octoposprime/op-design#294]
Design frames in the fairy tale theme you want.

**Comment by betulbodur00** [comment]
Fairytale themed frames (1-3)

![Fairytale Frame (1).png](https://github.com/user-attachments/assets/5e0ad409-c598-454f-a3b1-4a71f4d24f6b)

![Fairytale Frame (2).png](https://github.com/user-attachments/assets/b8c17226-cd53-46d3-b617-deaf6b3f3c7f)

![Fairytale Frame (3).png](https://github.com/user-attachments/assets/20f66c6a-9c1b-4608-86c8-f6006d4b7eb5)
