### ISSUE TITLE
Design Need for OctoFlight Game-1

### ISSUE THREAD

**Issue by mucahitgoncu** [octoposprime/op-design#30]
We need designs for the OctoFlight game that our game team will develop. I'm leaving the images below as an attachment for the needed designs. We want the design team to redesign the designs in the images to fit the Octopus Prime mascot.

![Mobile - Flappy Bird - Version 12 Sprites](https://github.com/octoposprime/op-design/assets/109546977/a004bc63-97c2-496a-9db5-065b989d3a3a)

**Comment by ikramylmz** [comment]
Ahmet Sinan Ünlü's designs for OctoFlight game
![a sinan ünlü OF ](https://github.com/octoposprime/op-design/assets/152586341/68a70abd-81d4-47d8-9974-23c792cc5e99)
![a sinan ünlü OF 4](https://github.com/octoposprime/op-design/assets/152586341/deb4c576-ca40-4af5-87bb-53d66439e840)
![a sinan ünlü OF 5](https://github.com/octoposprime/op-design/assets/152586341/fb688cca-6c73-4663-bd53-d887d4d21026)
![a sinan ünlü OF 6](https://github.com/octoposprime/op-design/assets/152586341/a73dcfbe-6e54-4ea7-802b-5af68b086182)
![a sinan ünlü OF 7](https://github.com/octoposprime/op-design/assets/152586341/376cbf9b-35c7-419b-88e6-de2c7272e273)
![a sinan ünlü OF 8](https://github.com/octoposprime/op-design/assets/152586341/9c01eeac-70a3-4e35-bf17-6325f6cac196)
![a sinan ünlü OF 9](https://github.com/octoposprime/op-design/assets/152586341/f57d56ed-6a30-41c5-a6e1-7c887294d865)
![a sinan ünlü OF 10](https://github.com/octoposprime/op-design/assets/152586341/34a2babc-e34b-4ae8-842f-d4e8036b8a7d)
![a sinan ünlü OF2](https://github.com/octoposprime/op-design/assets/152586341/c1c72c31-dd53-4af0-9ae8-675906d754a8)
![a sinan ünlü3](https://github.com/octoposprime/op-design/assets/152586341/510e1c1e-524d-4dbb-8953-8e7857363ac4)
