### ISSUE TITLE
Backend Icons and Badges-3

### ISSUE THREAD

**Issue by aleyna0f** [octoposprime/op-design#31]
In the OctopOs Prime project, one of the 8 teams, namely the Backend Team, requires the following designs from the Design Team:

- Designing the main icon for the Backend Team
- Designing 10 badges that determine the levels of members in the Backend Team
    - Obtaining the outputs as an icon
     - Obtaining the outputs in PNG format

**The badge names for the Backend Team are listed below.**
1) Silver Seed
2) Budding Sprout
3) Shining Leaf
4) Wisdom Tree
5) Crystal River    +
6) Mountain of Thought  +
7) Star Voyager   +
8) Beacon Captain
9) Sun Throne
10) Galaxy Lord

The works in icon format (.ico extension files) will be uploaded to the op-design repository's **Src/2D/Badges/Backend/Ico** directory, and those in PNG format (.png extension files) will be uploaded to the op-design repository's **Src/2D/Badges/Backend/Png** directory.

**The standardization of file names for the uploaded files will be as follows:**
`<Date>-<description of the logo>(<size>).<file extension>`
Example:
07-03-24-op-logo-black-and-blue-colors-futuristic-laboratory-setting(1280x720).jpg
08-03-24-op-logo-sleek-and-futuristic-clean-white-background(1280x720).jpg

**Comment by ikramylmz** [comment]
CYRSTAL RIVER

![Image](https://github.com/octoposprime/op-design/assets/152586341/c14814fa-fe7c-4809-a31a-bc947ae1cb65)

MOUNTAIN OF THOUGHT

![Image](https://github.com/octoposprime/op-design/assets/152586341/0e0ea256-b44a-40db-bcb7-ab4a5d2ca8d6)

STAR VOYAGER

![Image](https://github.com/octoposprime/op-design/assets/152586341/73d40194-c1d9-4d7f-bb00-6fbff47baf89)

**Comment by ikramylmz** [comment]
CYRSTAL RIVER

![Image](https://github.com/octoposprime/op-design/assets/152586341/671fb6e5-4b97-4861-be72-1bb5298d9808)

MOUNTAIN OF THOUGHT

![Image](https://github.com/octoposprime/op-design/assets/152586341/cc69ab90-0946-466d-9435-6f9d2184bd4c)

STAR VOYAGER

![Image](https://github.com/octoposprime/op-design/assets/152586341/0e31ea42-d8f6-4b2e-90a8-ce501d64a62f)
