### ISSUE TITLE
Design Icons and Badges-3

### ISSUE THREAD

**Issue by aleyna0f** [octoposprime/op-design#37]
In the OctopOs Prime project, one of the 8 teams, namely the Design Team, requires the following designs from the Design Team:

- Designing the main icon for the Design Team
- Designing 10 badges that determine the levels of members in the Design Team
    - Obtaining the outputs as an icon (32x32)
     - Obtaining the outputs in PNG format (1080x1080)

**The badge names for the Design Team are listed below.**

**1) Discovery Voyager**
Illustrator: Explore the interface, learn basic tools, and drawing techniques.
Blender: Explore the interface, learn basic modeling techniques, and navigation.

**2) Vector and Modeling Master**
Illustrator: Discover the power of vector drawing, design logos, icons, and illustrations.
Blender: Start creating simple 3D models.

**3) Color and Texture Alchemist**
Illustrator: Solve color theory, create eye-catching palettes.
Blender: Add texture and color to your models, making them realistic and appealing.

**4) Master of Letters and Animation**   
Illustrator: Enhance your designs with meaning and visual interest using typography.
Blender: Prepare to animate your models by learning rigging and animation techniques.

**5) Layers and Motion Wizard** +
Illustrator: Organize your designs with layers, create complex illustrations.
Blender: Learn to move your models realistically and smoothly.

**6) Effect and Light Master** +
Illustrator: Add special effects and textures to your designs with effect tools.
Blender: Add depth and atmosphere to your models using light and shadow.

**7) Pattern and Camera Sorcerer** +
Illustrator: Add rhythm and dynamism to your designs with pattern creation techniques.
Blender: Create impressive visuals using different camera angles and lenses.

**8) Visual and Simulation Wizard**
Illustrator: Enhance and enrich your designs using visual effects (VFX).
Blender: Create realistic effects using particle systems and physics simulations.

**9) Art and Render Hero**
Illustrator & Blender: Create 2D and 3D artworks reflecting your own style and vision.
Blender: Learn to turn your models into high-quality visuals.

**10) Gateway to Infinity**
Keep evolving and exploring innovations.
Embark on new horizons in the infinite universe of 2D and 3D design.

The works in icon format (.ico extension files) will be uploaded to the op-design repository's **Src/2D/Badges/Design/Ico** directory, and those in PNG format (.png extension files) will be uploaded to the op-design repository's **Src/2D/Badges/Design/Png** directory.

**The standardization of file names for the uploaded files will be as follows:**
`<Date>-<description of the logo>(<size>).<file extension>`
Example:
07-03-24-op-logo-black-and-blue-colors-futuristic-laboratory-setting(1280x720).jpg
08-03-24-op-logo-sleek-and-futuristic-clean-white-background(1280x720).jpg

**Comment by betulbodur00** [comment]
5,6 and 7th badges for the design team.

![Başlıksız2165_20240423104710.png](https://github.com/octoposprime/op-design/assets/158744085/84cca3d5-499e-4537-821e-71a51b97fdd4)

![Başlıksız2169_20240427090616.png](https://github.![Başlıksız2175_20240427083637.png](https://github.com/octoposprime/op-design/assets/158744085/2167152c-223a-4f23-9704-3ff597c79305)

d-7c![Başlıksız2177_20240427090645.png](https://github.com/octoposprime/op-design/assets/158744085/3daa563b-a4e5-4764-80fe-351e90ef85cc)

40427083914.png](https://github.com/octoposprime/op-design/assets/158744085/43c47b55-9baf-40a7-82ae-ad0928bc9fda)

şlıksız2133.png](https://github.com/octoposprime/op-design/assets/158744085/6c5b4545-1c1e-4db9-9cdc-2787f1a16450)

![Uploading Başlıksız2176_20240427083914.png …]()

![Uploading Başlıksız2177_20240427090645.png …]()

**Comment by betulbodur00** [comment]
5,6 and 7th badges for the design team.

5th badge

![Başlıksız2133.png](https://github.com/octoposprime/op-design/assets/158744085/65721be9-7b98-4a08-8faa-fd285ee1314a)

![Başlıksız2165_20240423104710.png](https://github.com/octoposprime/op-design/assets/158744085/9d95219c-0c2f-4a3b-bca9-5e9c6aab6431)

6th badge

![Başlıksız2175_20240427083637.png](https://github.com/octoposprime/op-design/assets/158744085/deaa751e-de68-413e-867d-98e0656891d3)

![Başlıksız2176_20240427083914.png](https://github.com/octoposprime/op-design/assets/158744085/e3bc24a0-a7b2-48c5-b98a-dc0af21b0247)

7th badge

![Başlıksız2169_20240427090616.png](https://github.com/octoposprime/op-design/assets/158744085/690656ff-3821-4499-9292-c13cb517c6dc)

![Başlıksız2177_20240427090645.png](https://github.com/octoposprime/op-design/assets/158744085/ccf873ca-4ca7-4027-8639-efc5194baf31)

**Comment by betulbodur00** [comment]
Non Pixelated Design Badges (5-7)

5th Badge
![Başlıksız2233.png](https://github.com/octoposprime/op-design/assets/158744085/919c8450-e7f7-49a8-a9eb-24b1ea7f8fc7)

6th Badge
![Başlıksız2234.png](https://github.com/octoposprime/op-design/assets/158744085/11f2c514-d157-450d-a152-9989262dcb1b)

7th Badge
![Başlıksız2236.png](https://github.com/octoposprime/op-design/assets/158744085/7dff3a8f-e7ae-46ef-8e99-6c1695ebfd22)
