### ISSUE TITLE
Design Icons and Badges-4 (the last three badges)

### ISSUE THREAD

**Issue by ikramylmz** [octoposprime/op-design#47]
In the OctopOs Prime project, one of the 8 teams, namely the Design Team, requires the following designs from the Design Team:

Designing the main icon for the Design Team
Designing 10 badges that determine the levels of members in the Design Team
Obtaining the outputs as an icon (32x32)
Obtaining the outputs in PNG format (1080x1080)
The badge names for the Design Team are listed below.

1) Discovery Voyager
Illustrator: Explore the interface, learn basic tools, and drawing techniques.
Blender: Explore the interface, learn basic modeling techniques, and navigation.

2) Vector and Modeling Master
Illustrator: Discover the power of vector drawing, design logos, icons, and illustrations.
Blender: Start creating simple 3D models.

3) Color and Texture Alchemist
Illustrator: Solve color theory, create eye-catching palettes.
Blender: Add texture and color to your models, making them realistic and appealing.

4) Master of Letters and Animation
Illustrator: Enhance your designs with meaning and visual interest using typography.
Blender: Prepare to animate your models by learning rigging and animation techniques.

5) Layers and Motion Wizard 
Illustrator: Organize your designs with layers, create complex illustrations.
Blender: Learn to move your models realistically and smoothly.

6) Effect and Light Master 
Illustrator: Add special effects and textures to your designs with effect tools.
Blender: Add depth and atmosphere to your models using light and shadow.

7) Pattern and Camera Sorcerer 
Illustrator: Add rhythm and dynamism to your designs with pattern creation techniques.
Blender: Create impressive visuals using different camera angles and lenses.

8) Visual and Simulation Wizard+
Illustrator: Enhance and enrich your designs using visual effects (VFX).
Blender: Create realistic effects using particle systems and physics simulations.

9) Art and Render Hero+
Illustrator & Blender: Create 2D and 3D artworks reflecting your own style and vision.
Blender: Learn to turn your models into high-quality visuals.

10) Gateway to Infinity+
Keep evolving and exploring innovations.
Embark on new horizons in the infinite universe of 2D and 3D design.

The works in icon format (.ico extension files) will be uploaded to the op-design repository's Src/2D/Badges/Design/Ico directory, and those in PNG format (.png extension files) will be uploaded to the op-design repository's Src/2D/Badges/Design/Png directory.

The standardization of file names for the uploaded files will be as follows:
<Date>-<description of the logo>(<size>).<file extension>
Example:
07-03-24-op-logo-black-and-blue-colors-futuristic-laboratory-setting(1280x720).jpg
08-03-24-op-logo-sleek-and-futuristic-clean-white-background(1280x720).jpg

**Comment by betulbodur00** [comment]
Design Badges (8-10)

8th Badge
![Başlıksız2219_20240501231311.png](https://github.com/octoposprime/op-design/assets/158744085/9bd2cdbc-b0b2-4057-ab6b-f85682282c50)

![Başlıksız2226_20240501231328.png](https://github.com/octoposprime/op-design/assets/158744085/f14e973a-ac3f-4b5c-90cc-4f578f0fc667)

9th Badge
![Başlıksız2223_20240501230554.png](https://github.com/octoposprime/op-design/assets/158744085/4b84dbc6-dbaf-459a-a08e-020ba4ec651e)

![Başlıksız2222_20240501230519.png](https://github.com/octoposprime/op-design/assets/158744085/94a2dec6-187f-4c54-8a51-a1bb3f705864)

10th Badge
First Alternative
![Başlıksız2225_20240501231111.png](https://github.com/octoposprime/op-design/assets/158744085/e6dcd479-82b0-49bd-9608-c5189c1e5702)

![Başlıksız2224_20240501231054.png](https://github.com/octoposprime/op-design/assets/158744085/8d9d5d72-f2ca-4336-bd1e-291f3edec6f1)

Second Alternative
![Başlıksız2203_20240427235557.png](https://github.com/octoposprime/op-design/assets/158744085/0ba9b4f4-0d2b-4ec5-9d8d-7e609a0ccb76)

![Başlıksız2204_20240427235616.png](https://github.com/octoposprime/op-design/assets/158744085/f2c1a3f8-8ce5-4e08-bbf7-e45990933217)

**Comment by betulbodur00** [comment]
Non Pixelated Design Badges (8-10)

8th Badge
![Başlıksız2238.png](https://github.com/octoposprime/op-design/assets/158744085/b25a050a-debf-43af-9f7d-07df41cfc865)

9th Badge
![Başlıksız2239.png](https://github.com/octoposprime/op-design/assets/158744085/38eafa25-eac2-403c-814d-f8648272cd9b)

10th Badge
![Başlıksız2240.png](https://github.com/octoposprime/op-design/assets/158744085/8c1ba37a-5729-4f00-b653-137599822040)
