### ISSUE TITLE
Design Need for OctoFlight Game-2

### ISSUE THREAD

**Issue by aleyna0f** [octoposprime/op-design#53]
what the game team leader wants from the design team:

  -We need designs for the OctoFlight game that our game team will develop. I'm leaving the images below as an attachment for the needed designs. We want the design team to redesign the designs in the images to fit the Octopus Prime mascot.

![Mobile - Flappy Bird - Version 12 Sprites](https://github.com/octoposprime/op-design/assets/109546977/a004bc63-97c2-496a-9db5-065b989d3a3a)

**Comment by ikramylmz** [comment]
![a sinan ünlü OF ](https://github.com/octoposprime/op-design/assets/152586341/0a76d604-c7bd-4a63-8eb2-59271c08fd24)
![a sinan ünlü OF 4](https://github.com/octoposprime/op-design/assets/152586341/4ba6e464-5842-41ef-8923-4c3f654da2b1)
![a sinan ünlü OF 5](https://github.com/octoposprime/op-design/assets/152586341/f329edc8-b6a2-46ae-9c40-f88145eafde2)
![a sinan ünlü OF 6](https://github.com/octoposprime/op-design/assets/152586341/77c880eb-bc4b-42be-b9d1-23740d6ee73b)
![a sinan ünlü OF 7](https://github.com/octoposprime/op-design/assets/152586341/b90e9f0a-afe9-43cf-b508-f993de3a4605)
![a sinan ünlü OF 8](https://github.com/octoposprime/op-design/assets/152586341/ab5a56d3-a334-4680-acd9-7916b26c75c0)
![a sinan ünlü OF 9](https://github.com/octoposprime/op-design/assets/152586341/12b089e5-92d4-44c6-8edf-3c80ba8f834c)
![a sinan ünlü OF 10](https://github.com/octoposprime/op-design/assets/152586341/4689cd9e-ea99-43a0-a983-602fee272b5b)
![a sinan ünlü OF2](https://github.com/octoposprime/op-design/assets/152586341/548cd9b5-1888-4d99-be31-9feae3baaa08)
![a sinan ünlü3](https://github.com/octoposprime/op-design/assets/152586341/a1401f33-fa9f-4900-8cd5-47e65a408125)

**Comment by ikramylmz** [comment]
İkram Yılmaz's designs for OctoFlight game
![OctoFlight everything-01](https://github.com/octoposprime/op-design/assets/152586341/e2f4fdbc-d831-4bc0-a378-2072dae1905e)
![OctoFlight everything-02](https://github.com/octoposprime/op-design/assets/152586341/4233de48-15da-431f-a94c-81f55908e45c)

**Comment by ikramylmz** [comment]
Betül Bodur's designs for OctoFlight game
![BB OF  BG denizatlı DAY](https://github.com/octoposprime/op-design/assets/152586341/7c9a3fc0-e30b-47e0-a002-d9eb7addd055)
![BB OF BG denizatlı NİGHT](https://github.com/octoposprime/op-design/assets/152586341/e0d33178-75bb-4f0f-ad98-08b8d5e61c7d)
![bb of octopos 1](https://github.com/octoposprime/op-design/assets/152586341/b3d3c2af-dce3-4dc0-9922-1e4bc4c3e4c4)
![bb of octopos 2](https://github.com/octoposprime/op-design/assets/152586341/254e241e-869c-4f9d-a3bd-2d2fc2aa6ba5)
![bb of octopos 3](https://github.com/octoposprime/op-design/assets/152586341/eaff45f8-2da6-43a8-b1d8-a360b77db07a)
![bb of octopos 4](https://github.com/octoposprime/op-design/assets/152586341/9f8e7725-587a-49e8-88a7-47796ae49a58)
![bb of octopos 5](https://github.com/octoposprime/op-design/assets/152586341/3dfbc5f7-5e37-432d-94fe-3d0558b3fccd)
![bb of octopos 6](https://github.com/octoposprime/op-design/assets/152586341/adbddc24-e172-43c5-883d-20cb914f5b17)
![bb of octopos 7](https://github.com/octoposprime/op-design/assets/152586341/75351535-579d-4738-844f-b518af80b36d)
![bb of octopos 8](https://github.com/octoposprime/op-design/assets/152586341/27872db8-5df5-42e9-8eaf-92ddff46a8d1)
![bb of octopos 9](https://github.com/octoposprime/op-design/assets/152586341/1e5fb82b-6281-435e-aeb6-9a89ad3300ed)
![bb of octopos 10](https://github.com/octoposprime/op-design/assets/152586341/a63b0e77-8c4a-4c4e-936b-af45e19c8db3)
![bb of octopos 11](https://github.com/octoposprime/op-design/assets/152586341/3724c9d7-d3b2-447a-a8ad-8b7161ba7fbb)
![bb of octopos 12](https://github.com/octoposprime/op-design/assets/152586341/61acc3ed-01a5-45f1-8603-4d051e4b429c)

![betül bodur of bg  day](https://github.com/octoposprime/op-design/assets/152586341/12078c00-0e4c-4c49-869e-0ad1e05f9da6)
![betül bodur of bg night gif](https://github.com/octoposprime/op-design/assets/152586341/6aab646a-884a-49fe-9f47-ed9ba60e2d75)
![betül bodur of bg night](https://github.com/octoposprime/op-design/assets/152586341/ec23b160-3f3b-4bdf-837c-ba48085c2950)
![bb of 1](https://github.com/octoposprime/op-design/assets/152586341/678c52d7-790c-4aff-b48f-d1d3cbdabb1f)
![bb of 3](https://github.com/octoposprime/op-design/assets/152586341/aea92976-d88f-4659-bb8a-7d656e0e60dd)
![bb of 4](https://github.com/octoposprime/op-design/assets/152586341/2aed5a30-8745-472c-946c-fd0d1a08282f)
![bb of 5](https://github.com/octoposprime/op-design/assets/152586341/99f2abad-618e-404e-a7fd-1535b56bbf2f)
![bb of 6](https://github.com/octoposprime/op-design/assets/152586341/ba15a966-dcdc-4ccc-ba37-a3f42d3fd9a3)
![bb of 7](https://github.com/octoposprime/op-design/assets/152586341/6d45794d-01f4-4100-b0a3-7ef392953340)
![bb of 8](https://github.com/octoposprime/op-design/assets/152586341/6f209054-4790-41e0-a6ec-9810b65d8641)
![bb of 9](https://github.com/octoposprime/op-design/assets/152586341/4e963cde-ff65-4c5e-ae75-70ba921dfb28)
![bb of 10](https://github.com/octoposprime/op-design/assets/152586341/0da8c402-3993-42be-a0b6-fdb716b449f5)
![bb of2](https://github.com/octoposprime/op-design/assets/152586341/aeb2fcb6-b8eb-4c2e-9457-5504041dbabd)
![BB OF  BG denizatlı DAY](https://github.com/octoposprime/op-design/assets/152586341/82f913a4-49ee-4240-8ca0-9aae2fa47275)
