### ISSUE TITLE
Design Need for OctoFlight Game-3

### ISSUE THREAD

**Issue by aleyna0f** [octoposprime/op-design#57]
Making texture and color designs for OctopOs Prime game character for OctoFlight game.

You need to design cute octopuses in different colors and textures, colors and textures can be preferred according to the concept of the game.

Let's present the images in 1920x1080 and on a single page.

**Comment by betulbodur00** [comment]
Different colored and textured designs for the OctoFlight game:

![Başlıksız2254_20240507222208.png](https://github.com/octoposprime/op-design/assets/158744085/e3817480-3b02-4295-b475-759f97ac9b9e)

**Comment by ikramylmz** [comment]
colored and textured Octopuses that I designed
![OctoFlight texture and color](https://github.com/octoposprime/op-design/assets/152586341/a2acf6dc-0afe-4ce7-b5b6-91d743ba831e)
