### ISSUE TITLE
Badge Frame Design of OctopOS Prime Teams

### ISSUE THREAD

**Issue by aleyna0f** [octoposprime/op-design#58]
Designing and deciding on the colors of the different colored frames for each level of our 10-level badges to represent the OctopOs Prime 8 team.

The size of the frames should be 1080x1080 and the codes of the colors you choose should be added.

**Comment by ikramylmz** [comment]
FRAMES FOR BADGES THAT I DESIGNED
![1- bronz frame 1](https://github.com/octoposprime/op-design/assets/152586341/b9d26f13-c956-4b29-bda3-30668babfcc6)

![2- bronz frame 2](https://github.com/octoposprime/op-design/assets/152586341/1696ea94-3bd0-4158-818a-cb906ed408f6)
![3- bronz frame 3](https://github.com/octoposprime/op-design/assets/152586341/d9a48193-f21f-4607-be30-460cb817181a)
![4-silver frame 1](https://github.com/octoposprime/op-design/assets/152586341/53db3a50-5772-4a27-bd4b-570a7ed1d25a)
![5-frame silver 2](https://github.com/octoposprime/op-design/assets/152586341/abba4800-f7ee-4170-9cf5-441a826d7159)
![7-gold frame 1](https://github.com/octoposprime/op-design/assets/152586341/cd5565d2-b343-4e31-8994-d748eec0e2b6)
![6-silver frame 3](https://github.com/octoposprime/op-design/assets/152586341/f283cc63-58e0-4b4e-aa71-c65ff15ca8b4)
![8-gold frame 2](https://github.com/octoposprime/op-design/assets/152586341/a79b96eb-6591-4b2d-a1af-ab655e6e8910)
![9-gold frame 3](https://github.com/octoposprime/op-design/assets/152586341/b1ab7687-a108-46a1-b1eb-20e0b0efefee)
![10-cyrstal frame 10](https://github.com/octoposprime/op-design/assets/152586341/80d1ba0e-6935-4065-98bc-28befac95b48)
