### ISSUE TITLE
OctopOS Prime's Facial Expressions-4

### ISSUE THREAD

**Issue by aleyna0f** [octoposprime/op-design#64]
Different kinds of facial expressions are required for OctopOS Prime. 

You can draw any facial expressions you like.

**Comment by betulbodur00** [comment]
Facial expressions of OctopOs Prime



![Başlıksız2202_20240427215919.png](https://github.com/octoposprime/op-design/assets/158744085/c18671ff-2a10-4549-aa5b-64066a825f13)

![Başlıksız2202_20240427215806.png](https://github.com/octoposprime/op-design/assets/158744085/1f72fafa-02fc-49e5-a89b-78e62d795660)

![Başlıksız2202_20240427215730.png](https://github.com/octoposprime/op-design/assets/158744085/6b5fc3e7-8b60-4191-b242-0b3a40401b08)

![Başlıksız2202_20240427220010.png](https://github.com/octoposprime/op-design/assets/158744085/075e1146-1222-4962-8941-88911f42c889)

![Başlıksız2202_20240427215853.png](https://github.com/octoposprime/op-design/assets/158744085/5172d8e4-4357-42e8-bbcd-0ca6b2ccf87c)

![Başlıksız2202_20240427220322.png](https://github.com/octoposprime/op-design/assets/158744085/9dc40d47-2898-4dff-b30b-8849c6597ba6)

![Başlıksız2202_20240427215832.png](https://github.com/octoposprime/op-design/assets/158744085/1210a852-e3b1-42c0-9c72-24a1651f980b)

![Başlıksız2202_20240427221203.png](https://github.com/octoposprime/op-design/assets/158744085/36669312-9d86-430e-be0d-821388541e80)

![Başlıksız2202_20240427221830.png](https://github.com/octoposprime/op-design/assets/158744085/d7a1027d-c5c9-426a-b408-bc7a2450fead)

![Başlıksız2202_20240427220802.png](https://github.com/octoposprime/op-design/assets/158744085/f11e1a8c-d45a-4a8d-bce9-5836a3cbee11)

![Başlıksız2202_20240427222000.png](https://github.com/octoposprime/op-design/assets/158744085/762fc936-f44b-45bc-a715-5e5367b38b68)

![Başlıksız2202_20240427220559.png](https://github.com/octoposprime/op-design/assets/158744085/a5388aed-7c20-4036-a877-4f0846e18b0a)

![Başlıksız2202_20240427221217.png](https://github.com/octoposprime/op-design/assets/158744085/b6e4b695-80d2-4217-a771-468278be9c28)

![Başlıksız2202_20240427221558.png](https://github.com/octoposprime/op-design/assets/158744085/00d3e639-3db1-4517-bc3b-03645bdd9944)

![Başlıksız2202_20240427221018.png](https://github.com/octoposprime/op-design/assets/158744085/2d493583-b236-42c6-8b27-a4fe97d5d408)

![Başlıksız2257_20240507155033.png](https://github.com/octoposprime/op-design/assets/158744085/2893c6d2-d4c3-4b1f-ac0e-26ea7bd59cba)

![Başlıksız2241_20240507180314.png](https://github.com/octoposprime/op-design/assets/158744085/75e14fc9-4d99-4bef-8b50-b14a4d64e5b0)

![Başlıksız2241_20240507180923.png](https://github.com/octoposprime/op-design/assets/158744085/439ca3c7-8cf6-447f-8b1e-b2bd39b4d6a5)

![Başlıksız2241_20240507181434.png](https://github.com/octoposprime/op-design/assets/158744085/d001a179-347f-48b2-a3e8-e9960f2c55d7)

![Başlıksız2241_20240507175806.png](https://github.com/octoposprime/op-design/assets/158744085/0400c9a1-799c-4028-b220-df3b1df8c299)

![Başlıksız2241_20240507180450.png](https://github.com/octoposprime/op-design/assets/158744085/2540b57b-c0d6-40dc-9c96-3f9538823c5f)

![Başlıksız2241_20240507175726.png](https://github.com/octoposprime/op-design/assets/158744085/b0fb2779-22f7-4a84-b5dc-99279467df63)

![Başlıksız2241_20240507175930.png](https://github.com/octoposprime/op-design/assets/158744085/5918e875-35b0-4fe4-80d4-f1bfab2bf97e)

![Başlıksız2241_20240507180119.png](https://github.com/octoposprime/op-design/assets/158744085/712c69f2-66e7-4e9b-9a7d-4020aa29d7fe)

![Başlıksız2257_20240507193240.png](https://github.com/octoposprime/op-design/assets/158744085/db426c12-f16b-47fc-86ee-8548cfb82784)

![Başlıksız2257_20240507195033.png](https://github.com/octoposprime/op-design/assets/158744085/0f816df4-4130-4abe-a7ca-bd8497a8cde4)

![Başlıksız2241_20240507183519.png](https://github.com/octoposprime/op-design/assets/158744085/e520b185-3185-4d23-9018-5a279eeee2c0)

![Başlıksız2257_20240507194436.png](https://github.com/octoposprime/op-design/assets/158744085/45009344-7ece-4f2d-8486-b102f5d0427a)

![Başlıksız2257_20240507195246.png](https://github.com/octoposprime/op-design/assets/158744085/d29a58d9-fac6-426e-877f-67be49065338)

![Başlıksız2241_Geri Yüklendi_20240507225227.png](https://github.com/octoposprime/op-design/assets/158744085/f3b2c35a-dbcb-4dd0-9984-3fd187c91d74)

![Başlıksız2257_20240509131205.png](https://github.com/octoposprime/op-design/assets/158744085/6a70f31d-b604-49e0-affe-ba33c4910f10)

![Başlıksız2257_20240509132017.png](https://github.com/octoposprime/op-design/assets/158744085/4649684f-f94a-423c-a127-06d09393e8a2)

![Başlıksız2257_20240509130910.png](https://github.com/octoposprime/op-design/assets/158744085/af33d81c-8101-4281-a589-3ccc7d222339)

![Başlıksız2257_20240509130141.png](https://github.com/octoposprime/op-design/assets/158744085/7919cfba-629f-4c8d-a469-c9eeb830b39b)

![Başlıksız2257_20240509131721.png](https://github.com/octoposprime/op-design/assets/158744085/617aec30-3c25-475a-aedf-bc9976f17362)

![Başlıksız2257_20240509130338.png](https://github.com/octoposprime/op-design/assets/158744085/95367fb6-e8e4-495b-add9-fa3d77c2680d)

![Başlıksız2257_20240509131345.png](https://github.com/octoposprime/op-design/assets/158744085/ce887737-84b2-4516-93d9-d9ffac1ed0ac)

Second version of facial expressions:

![Başlıksız2259_20240507210743.png](https://github.com/octoposprime/op-design/assets/158744085/f5345f2d-b249-44e2-bc36-b415e4036ab9)

![Başlıksız2259_20240507210719.png](https://github.com/octoposprime/op-design/assets/158744085/45f0ca6e-b9f7-4d51-a4ce-da486183fa39)

![Başlıksız2259_20240507210813.png](https://github.com/octoposprime/op-design/assets/158744085/228d7680-21df-4df3-8f3c-dce1ddb41d63)

![Başlıksız2259_20240507211130.png](https://github.com/octoposprime/op-design/assets/158744085/94af7ecb-53ee-4ec6-948b-52d063f819d4)

![Başlıksız2259_20240507210646.png](https://github.com/octoposprime/op-design/assets/158744085/f8e836c4-f5b3-43e7-9718-34e641921c72)

![Başlıksız2259_20240507210951.png](https://github.com/octoposprime/op-design/assets/158744085/595f7939-3634-43cf-8091-9a3321007949)

![Başlıksız2259_20240507211206.png](https://github.com/octoposprime/op-design/assets/158744085/21b972c4-6edc-401e-b175-a8a2ee247b7b)

![Başlıksız2259_20240507210913.png](https://github.com/octoposprime/op-design/assets/158744085/cdee7214-da8a-441a-b9af-67198d0426b0)

![Başlıksız2259_20240507211233.png](https://github.com/octoposprime/op-design/assets/158744085/47d70413-bf05-424c-8d9b-ce9571e7a66e)

![Başlıksız2259_20240507211312.png](https://github.com/octoposprime/op-design/assets/158744085/1218da5e-170b-4cbf-910f-92760d36ff1e)

![Başlıksız2259_20240507212638.png](https://github.com/octoposprime/op-design/assets/158744085/fb64d4cf-19c4-40bb-a76a-efe64e960323)

Bonus (Expressionless)

![Başlıksız2259_20240507210616.png](https://github.com/octoposprime/op-design/assets/158744085/581386c5-ad3b-48f3-b880-067f3be62638)

**Comment by betulbodur00** [comment]
Facial expressions of OctopOs Prime



![Başlıksız2202_20240427215919.png](https://github.com/octoposprime/op-design/assets/158744085/c18671ff-2a10-4549-aa5b-64066a825f13)

![Başlıksız2202_20240427215806.png](https://github.com/octoposprime/op-design/assets/158744085/1f72fafa-02fc-49e5-a89b-78e62d795660)

![Başlıksız2202_20240427215730.png](https://github.com/octoposprime/op-design/assets/158744085/ceb514ed-4b90-4241-8fed-c89651f7ba49)

![Başlıksız2202_20240427220010.png](https://github.com/octoposprime/op-design/assets/158744085/075e1146-1222-4962-8941-88911f42c889)

![Başlıksız2202_20240427215853.png](https://github.com/octoposprime/op-design/assets/158744085/5172d8e4-4357-42e8-bbcd-0ca6b2ccf87c)

![Başlıksız2202_20240427220322.png](https://github.com/octoposprime/op-design/assets/158744085/9dc40d47-2898-4dff-b30b-8849c6597ba6)

![Başlıksız2202_20240427215832.png](https://github.com/octoposprime/op-design/assets/158744085/1210a852-e3b1-42c0-9c72-24a1651f980b)

![Başlıksız2202_20240427221203.png](https://github.com/octoposprime/op-design/assets/158744085/36669312-9d86-430e-be0d-821388541e80)

![Başlıksız2202_20240427221830.png](https://github.com/octoposprime/op-design/assets/158744085/d7a1027d-c5c9-426a-b408-bc7a2450fead)

![Başlıksız2202_20240427220802.png](https://github.com/octoposprime/op-design/assets/158744085/f11e1a8c-d45a-4a8d-bce9-5836a3cbee11)

![Başlıksız2202_20240427222000.png](https://github.com/octoposprime/op-design/assets/158744085/762fc936-f44b-45bc-a715-5e5367b38b68)

![Başlıksız2202_20240427220559.png](https://github.com/octoposprime/op-design/assets/158744085/a5388aed-7c20-4036-a877-4f0846e18b0a)

![Başlıksız2202_20240427221217.png](https://github.com/octoposprime/op-design/assets/158744085/b6e4b695-80d2-4217-a771-468278be9c28)

![Başlıksız2202_20240427221558.png](https://github.com/octoposprime/op-design/assets/158744085/00d3e639-3db1-4517-bc3b-03645bdd9944)

![Başlıksız2202_20240427221018.png](https://github.com/octoposprime/op-design/assets/158744085/2d493583-b236-42c6-8b27-a4fe97d5d408)

![Başlıksız2257_20240507155033.png](https://github.com/octoposprime/op-design/assets/158744085/2893c6d2-d4c3-4b1f-ac0e-26ea7bd59cba)

![Başlıksız2241_20240507180314.png](https://github.com/octoposprime/op-design/assets/158744085/75e14fc9-4d99-4bef-8b50-b14a4d64e5b0)

![Başlıksız2241_20240507180923.png](https://github.com/octoposprime/op-design/assets/158744085/439ca3c7-8cf6-447f-8b1e-b2bd39b4d6a5)

![Başlıksız2241_20240507181434.png](https://github.com/octoposprime/op-design/assets/158744085/d001a179-347f-48b2-a3e8-e9960f2c55d7)

![Başlıksız2241_20240507175806.png](https://github.com/octoposprime/op-design/assets/158744085/0400c9a1-799c-4028-b220-df3b1df8c299)

![Başlıksız2241_20240507180450.png](https://github.com/octoposprime/op-design/assets/158744085/2540b57b-c0d6-40dc-9c96-3f9538823c5f)

![Başlıksız2241_20240507175726.png](https://github.com/octoposprime/op-design/assets/158744085/b0fb2779-22f7-4a84-b5dc-99279467df63)

![Başlıksız2241_20240507175930.png](https://github.com/octoposprime/op-design/assets/158744085/5918e875-35b0-4fe4-80d4-f1bfab2bf97e)

![Başlıksız2241_20240507180119.png](https://github.com/octoposprime/op-design/assets/158744085/712c69f2-66e7-4e9b-9a7d-4020aa29d7fe)

![Başlıksız2257_20240507193240.png](https://github.com/octoposprime/op-design/assets/158744085/db426c12-f16b-47fc-86ee-8548cfb82784)

![Başlıksız2257_20240507195033.png](https://github.com/octoposprime/op-design/assets/158744085/0f816df4-4130-4abe-a7ca-bd8497a8cde4)

![Başlıksız2241_20240507183519.png](https://github.com/octoposprime/op-design/assets/158744085/e520b185-3185-4d23-9018-5a279eeee2c0)

![Başlıksız2257_20240507194436.png](https://github.com/octoposprime/op-design/assets/158744085/45009344-7ece-4f2d-8486-b102f5d0427a)

![Başlıksız2257_20240507195246.png](https://github.com/octoposprime/op-design/assets/158744085/d29a58d9-fac6-426e-877f-67be49065338)

![Başlıksız2241_Geri Yüklendi_20240507225227.png](https://github.com/octoposprime/op-design/assets/158744085/f3b2c35a-dbcb-4dd0-9984-3fd187c91d74)

![Başlıksız2257_20240509131205.png](https://github.com/octoposprime/op-design/assets/158744085/6a70f31d-b604-49e0-affe-ba33c4910f10)

![Başlıksız2257_20240509132017.png](https://github.com/octoposprime/op-design/assets/158744085/4649684f-f94a-423c-a127-06d09393e8a2)

![Başlıksız2257_20240509130910.png](https://github.com/octoposprime/op-design/assets/158744085/af33d81c-8101-4281-a589-3ccc7d222339)

![Başlıksız2257_20240509130141.png](https://github.com/octoposprime/op-design/assets/158744085/7919cfba-629f-4c8d-a469-c9eeb830b39b)

![Başlıksız2257_20240509131721.png](https://github.com/octoposprime/op-design/assets/158744085/617aec30-3c25-475a-aedf-bc9976f17362)

![Başlıksız2257_20240509130338.png](https://github.com/octoposprime/op-design/assets/158744085/95367fb6-e8e4-495b-add9-fa3d77c2680d)

![Başlıksız2257_20240509131345.png](https://github.com/octoposprime/op-design/assets/158744085/ce887737-84b2-4516-93d9-d9ffac1ed0ac)

Second version of facial expressions:

![Başlıksız2259_20240507210743.png](https://github.com/octoposprime/op-design/assets/158744085/f5345f2d-b249-44e2-bc36-b415e4036ab9)

![Başlıksız2259_20240507210719.png](https://github.com/octoposprime/op-design/assets/158744085/45f0ca6e-b9f7-4d51-a4ce-da486183fa39)

![Başlıksız2259_20240507210813.png](https://github.com/octoposprime/op-design/assets/158744085/228d7680-21df-4df3-8f3c-dce1ddb41d63)

![Başlıksız2259_20240507211130.png](https://github.com/octoposprime/op-design/assets/158744085/94af7ecb-53ee-4ec6-948b-52d063f819d4)

![Başlıksız2259_20240507210646.png](https://github.com/octoposprime/op-design/assets/158744085/f8e836c4-f5b3-43e7-9718-34e641921c72)

![Başlıksız2259_20240507210951.png](https://github.com/octoposprime/op-design/assets/158744085/595f7939-3634-43cf-8091-9a3321007949)

![Başlıksız2259_20240507211206.png](https://github.com/octoposprime/op-design/assets/158744085/21b972c4-6edc-401e-b175-a8a2ee247b7b)

![Başlıksız2259_20240507210913.png](https://github.com/octoposprime/op-design/assets/158744085/cdee7214-da8a-441a-b9af-67198d0426b0)

![Başlıksız2259_20240507211233.png](https://github.com/octoposprime/op-design/assets/158744085/47d70413-bf05-424c-8d9b-ce9571e7a66e)

![Başlıksız2259_20240507211312.png](https://github.com/octoposprime/op-design/assets/158744085/1218da5e-170b-4cbf-910f-92760d36ff1e)

![Başlıksız2259_20240507212638.png](https://github.com/octoposprime/op-design/assets/158744085/fb64d4cf-19c4-40bb-a76a-efe64e960323)

Bonus (Expressionless)

![Başlıksız2259_20240507210616.png](https://github.com/octoposprime/op-design/assets/158744085/581386c5-ad3b-48f3-b880-067f3be62638)
