### ISSUE TITLE
Web Team's Company Logo Design

### ISSUE THREAD

**Issue by aleyna0f** [octoposprime/op-design#71]
Logo design for the Web Team's company "InoskyTech".
The size of the logo should be 1080x1080.

Desired design and color codes.

- #e4e0d7
- #3c4742

**Comment by zeyneptuvba** [comment]
Logo design for the Web Team's company "InoskyTech".


![inoskytech logo](https://github.com/octoposprime/op-design/assets/158461753/8661d986-f36c-42d2-948b-33f50e853202)
