### ISSUE TITLE
Backend Team's Company Logo Design

### ISSUE THREAD

**Issue by aleyna0f** [octoposprime/op-design#72]
Logo design for the Backend Team's for the company "Posinowa". 

The size of the logo should be 1080x1080.

Color codes.

Color codes.

- #b8bbc7
- #141e46

**Comment by ikramylmz** [comment]
![POSINOWA  AMBLEM](https://github.com/octoposprime/op-design/assets/152586341/08257e04-a315-44f4-a97d-10f05cb81174)
![POSINOWA LOGO](https://github.com/octoposprime/op-design/assets/152586341/3c6da4b8-a9ec-4e4d-bf6a-1d200c8dc5ff)
