### ISSUE TITLE
Game Team's Company Logo Design

### ISSUE THREAD

**Issue by aleyna0f** [octoposprime/op-design#73]
Logo design for the Game Team's company called "NVM Game". 

The size of the logo should be 1080x1080.

Color codes.

  - #E6E6DD
  - #2B2B2B

**Comment by nurbeyzaoztrk** [comment]
Logo design for the Game Team's company called "NVM Game".

![Image](https://github.com/octoposprime/op-design/assets/120026216/5a612465-90b5-43c1-b29c-b7396bdfdb33)
