### ISSUE TITLE
Design Team's Company Logo Design

### ISSUE THREAD

**Issue by aleyna0f** [octoposprime/op-design#75]
Logo design for the Design Team's for the company "NACCASH".

The size of the logo should be 1080x1080.

Color codes.

- #F1ECDF
- #3C4742
- #e67859
- #ee9a3c
- #000000
- #5b560f
- #dbd5d2
- #171716
- #100f0f
- #3a403d
- #49444e

**Comment by zeyneptuvba** [comment]
Logo design for the Design Team's for the company "NACCASH".

![2](https://github.com/octoposprime/op-design/assets/158461753/7e8ae8b8-5a84-4b56-bb96-c98712344486)
![3](https://github.com/octoposprime/op-design/assets/158461753/81138f50-787a-43ae-85cd-c24bd2be6360)
![4](https://github.com/octoposprime/op-design/assets/158461753/a48a098c-622a-456d-ab4b-916335b1fe6e)
![5](https://github.com/octoposprime/op-design/assets/158461753/a2d16064-239b-42b9-a569-439a1642dd39)
![6](https://github.com/octoposprime/op-design/assets/158461753/e87f8c2b-2eb9-4b9f-bd40-36878a2d3ff5)
![7](https://github.com/octoposprime/op-design/assets/158461753/0ab19ce6-8c3c-462c-8d75-5fb77b4a4d71)
![8](https://github.com/octoposprime/op-design/assets/158461753/9dbfae37-120c-4620-b857-1cf2307d9e4b)
![9](https://github.com/octoposprime/op-design/assets/158461753/39a77687-4e56-4cf6-bac4-dcbace3dfb5a)
![10](https://github.com/octoposprime/op-design/assets/158461753/d6af491f-7c79-440d-9328-37ad2963df17)
![11](https://github.com/octoposprime/op-design/assets/158461753/71d2de2c-5b52-4980-ba31-9bc15c94bfc8)
![12](https://github.com/octoposprime/op-design/assets/158461753/4c376498-4ec5-4825-8053-113fc7eb5a50)
![1](https://github.com/octoposprime/op-design/assets/158461753/66b60e15-7947-44f5-a70a-47c9f0270a1e)

**Comment by zeyneptuvba** [comment]
Logo design for the Design Team's for the company "NACCASH".


![1](https://github.com/octoposprime/op-design/assets/158461753/598ae430-21ec-4d19-ba67-367502c27cd1)
![2](https://github.com/octoposprime/op-design/assets/158461753/b78c06e4-3cf2-45c4-9031-ade324e6f18d)

**Comment by zeyneptuvba** [comment]
Logo design for the Design Team's for the company "NACCASH".


![naccash desıgn](https://github.com/octoposprime/op-design/assets/158461753/aab6290c-9bd4-4c93-b226-f70fc94e6687)
![naccash](https://github.com/octoposprime/op-design/assets/158461753/8e169c17-5fc0-43a1-8d5f-c6a474ea5cd7)
