### ISSUE TITLE
Ceramic Team's Company Logo Design

### ISSUE THREAD

**Issue by aleyna0f** [octoposprime/op-design#76]
Logo design for the Ceramics Team's company "Chomlex".

The size of the logo should be 1080x1080.

Color codes.

- #000000
- #FFFFFF

**Comment by esmanrshn** [comment]
Ceramic Team's Company Logo Design

![11](https://github.com/octoposprime/op-design/assets/128504391/22dbd83c-4c9f-4be1-8d9a-cbf74587e5ef)
