### ISSUE TITLE
Docs Team's Company Logo Design

### ISSUE THREAD

**Issue by aleyna0f** [octoposprime/op-design#77]
Logo design for the Docs Team's for the company "Ubn-Jr".

The size of the logo should be 1080x1080.

Color codes.

- #FFFFFF
- #D0D0D0
- #A1A1A1
- #585858
- #353535
- #090909

**Comment by mzarabaci** [comment]
![UBN12](https://github.com/octoposprime/op-design/assets/158720216/c5a7de21-100b-4625-8d0e-11364577d5c3)
