### ISSUE TITLE
DevOps Team's Company Logo Design

### ISSUE THREAD

**Issue by aleyna0f** [octoposprime/op-design#78]
Logo design for the DevOps Team's for the company " ResolveOps".

The size of the logo should be 1080x1080.

Color codes.

- #00127B
- #480303
- #1B1E64
- #581919

**Comment by esmanrshn** [comment]
DevOps Team's Company Logo Design

![Uploading Adsız tasarım.png…]()

**Comment by esmanrshn** [comment]
DevOps Team's Company Logo Design

![RESOLVEOPS (5)](https://github.com/octoposprime/op-design/assets/128504391/3799e7b3-adc8-41cd-b3c5-b579c4080a1e)
