### ISSUE TITLE
Web Team's Company Business Card Design

### ISSUE THREAD

**Issue by ikramylmz** [octoposprime/op-design#88]
Business card design for Web Team's company  "InoskyTech".
The size of the card should be 8,5 x 5 cm.
There should be a photo of OctopOSPrime website on the back of the card and contact information and the logo on the front.

Desired design and color codes.

  #e4e0d7
  #3c4742

**Comment by zeyneptuvba** [comment]
Business card design for Web Team's company "InoskyTech".

![1 kopyası](https://github.com/octoposprime/op-design/assets/158461753/d46483de-e51d-4c63-8bc6-a316c937d63b)
![2 kopyası](https://github.com/octoposprime/op-design/assets/158461753/6e6aab38-7f50-4aea-9445-2f2535d09e1f)
