### ISSUE TITLE
Game Team's Company Business Card Design

### ISSUE THREAD

**Issue by ikramylmz** [octoposprime/op-design#90]
Busines card design for Game Team's company "NVM Game".
The size of the card should be 8,5 x 5 cm.
There should be a photo of OctopOSPrime website on the back of the card and contact information and the logo on the front.

Desired design and color codes.

  #E6E6DD
  #2B2B2B

**Comment by nurbeyzaoztrk** [comment]
![Image](https://github.com/octoposprime/op-design/assets/120026216/a1c391bb-7f5e-4bba-bd65-be05c15b5946)


![Image](https://github.com/octoposprime/op-design/assets/120026216/14ccf1d7-ee38-4620-9c33-9c888db7899b)
