### ISSUE TITLE
Mobil Team's Company Business Card Design

### ISSUE THREAD

**Issue by ikramylmz** [octoposprime/op-design#91]
Business card design for Mobil Team's company "MODEST".
The size of the card should be 8,5 x 5 cm.
There should be a photo of OctopOSPrime website on the back of the card and contact information and the logo on the front.

Desired design and color codes.

   #FCB61A
   R:10 G:61 B:51

   #F4F3FA
   R:244 G: 243 B:240

**Comment by aleyna0f** [comment]
![mobil kartvizit](https://github.com/octoposprime/op-design/assets/118018067/4d213293-8c5c-4cb2-b932-132f66f2adf2)

![ahmet berat kartvizit-01](https://github.com/octoposprime/op-design/assets/118018067/11e5783e-3bb8-4c49-b93f-ec8295485259)

![nedim toymuş kartvizit-01](https://github.com/octoposprime/op-design/assets/118018067/e00184ac-fa19-4b55-9d35-6d3d010b27ab)
