### ISSUE TITLE
Design Team's Company Business Card Design

### ISSUE THREAD

**Issue by ikramylmz** [octoposprime/op-design#92]
Business card design for Design Team's company "NACCASH".
The size of the card should be 8,5 x 5 cm.
There should be a photo of OctopOSPrime website on the back of the card and contact information and the logo on the front.

Desired design and color codes.

  #F1ECDF
  #3C4742
  #e67859
  #ee9a3c
  #000000
  #5b560f
  #dbd5d2
  #171716
  #100f0f
  #3a403d
  #49444e

**Comment by zeyneptuvba** [comment]
Business card design for Design Team's company "NACCASH".

![1](https://github.com/octoposprime/op-design/assets/158461753/10f86111-1e76-4fd5-aa69-05fadc7b084f)
![2](https://github.com/octoposprime/op-design/assets/158461753/fa982c96-a11b-4df1-8ac3-3fe3e7762732)
