### ISSUE TITLE
Ceramic Team's Company Business Card Design

### ISSUE THREAD

**Issue by ikramylmz** [octoposprime/op-design#93]
Business card design for Ceramic Team's company "Chomlex".
The size of the card should be 8,5 x 5 cm.
There should be a photo of OctopOSPrime website on the back of the card and contact information and the logo on the front.

Desired design and color codes.

  #000000
  #FFFFFF

**Comment by esmanrshn** [comment]
Ceramic Team's Company Business Card Design

![5](https://github.com/octoposprime/op-design/assets/128504391/cac9843f-3dc9-4df1-b567-207177c8f750)

![4](https://github.com/octoposprime/op-design/assets/128504391/f64d0c6e-6979-484d-9e3e-d04f2591bc58)
