### ISSUE TITLE
Docs Team's Company Business Card Design 

### ISSUE THREAD

**Issue by ikramylmz** [octoposprime/op-design#94]
Business card design for Docs Team's company "Ubn-Jr".
The size of the card should be 8,5 x 5 cm.
There should be a photo of OctopOSPrime website on the back of the card and contact information and the logo on the front.

Desired design and color codes.

  #FFFFFF
  #D0D0D0
  #A1A1A1
  #585858
  #353535
  #090909

**Comment by mzarabaci** [comment]
![ubnjr_](https://github.com/octoposprime/op-design/assets/158720216/cf3c4030-409e-455d-9865-a2a51fb8a011)
