### ISSUE TITLE
DevOps Team's Company Business Card Design

### ISSUE THREAD

**Issue by ikramylmz** [octoposprime/op-design#95]
Business card design for DevOps Team's company "ResolveOps".
The size of the card should be 8,5 x 5 cm.
There should be a photo of OctopOSPrime website on the back of the card and contact information and the logo on the front.

Desired design and color codes.

  #00127B
  #480303
  #1B1E64
  #581919

**Comment by esmanrshn** [comment]
DevOps Team's Company Business Card Design


![Blue and white business card (1)](https://github.com/octoposprime/op-design/assets/128504391/1159d84e-f43a-4cf4-afee-630b9fd2c717)


![Blue White Modern Business Consultant Business Card](https://github.com/octoposprime/op-design/assets/128504391/77b33157-7bb3-4d17-8748-349fc46ab72a)
