### ISSUE TITLE
Electronic - Mechanic Team's Company Business Card Design

### ISSUE THREAD

**Issue by ikramylmz** [octoposprime/op-design#96]
Business card design for Electronic - Mechanic Team's company "ComNal".
The size of the card should be 8,5 x 5 cm.
There should be a photo of OctopOSPrime website on the back of the card and contact information and the logo on the front.

Desired design and color codes.

  #FDE100
  #000000

**Comment by aleyna0f** [comment]
![elecktonic kartvizit-0 0-01](https://github.com/octoposprime/op-design/assets/118018067/a8ff40ae-1d57-43fc-8c28-b03bec5f5feb)
![comnal-01](https://github.com/octoposprime/op-design/assets/118018067/3e2c6ed7-afe0-46b9-a6c4-e1e57209004a)
![yusuf yılmaz kartvizitt-01](https://github.com/octoposprime/op-design/assets/118018067/cf53f4af-be3f-42e1-9c55-57e9c6c395a7)
![babür akbaş kartvizit2-01](https://github.com/octoposprime/op-design/assets/118018067/c332c649-4dbc-4bb1-8f06-e432051d800b)
